#include "MLLibraryBase.h"

namespace MLLibrary {


    /** 
     *  MLLibraryBase provide a basic interface for MLLibrary modules to be follow.
     *  1. int pwrp()
     *  2. int init()
     *  3. int pwrdn()
     *  @author garmin
     *  @version 1.0
     */



void MLLibraryBase::pwrp()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-63ded821:144b56a81eb:-8000:0000000000000967 begin
{
}
// section 127-0-1-1-63ded821:144b56a81eb:-8000:0000000000000967 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MLLibraryBase::init()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-63ded821:144b56a81eb:-8000:0000000000000969 begin
{
}
// section 127-0-1-1-63ded821:144b56a81eb:-8000:0000000000000969 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void MLLibraryBase::pwrdn()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-63ded821:144b56a81eb:-8000:000000000000096B begin
{
}
// section 127-0-1-1-63ded821:144b56a81eb:-8000:000000000000096B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace MLLibrary */
